apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: writeitupx

resources:
  - ../../base

configMapGenerator:
  - name: app-config
    literals:
      - node_env=production
      - api_url=https://api.writeitupx.com
      - client_url=https://writeitupx.com

secretGenerator:
  - name: app-secrets
    envs:
      - .env.prod

patches:
  - target:
      kind: Deployment
      name: client
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: server
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3 