apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - client-deployment.yaml
  - server-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: writeitupx
  app.kubernetes.io/part-of: writeitupx 