name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Deploy server first
    - name: Deploy Server to Vercel
      working-directory: ./server
      run: |
        echo "Installing Vercel CLI..."
        npm i -g vercel
        echo "Deploying server..."
        vercel deploy . --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --scope keenpaul29s-projects
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SERVER_PROJECT_ID }}

    # Then deploy client
    - name: Deploy Client to Vercel
      working-directory: ./client
      run: |
        echo "Installing Vercel CLI..."
        npm i -g vercel
        echo "Deploying client..."
        vercel deploy . --prod --yes --token=${{ secrets.VERCEL_TOKEN }} --scope keenpaul29s-projects
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_CLIENT_PROJECT_ID }}


