name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    
    # Client build
    - name: Setup Node.js for Client
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: client/package-lock.json
    
    - name: Install Client Dependencies
      working-directory: ./client
      run: npm ci
    
    - name: Build Client
      working-directory: ./client
      run: npm run build
    
    # Server build
    - name: Setup Node.js for Server
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    
    - name: Install Server Dependencies
      working-directory: ./server
      run: npm ci
    
    - name: Build Server
      working-directory: ./server
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: Production
      url: ${{ steps.deploy-client.outputs.preview-url }}

    steps:
    - uses: actions/checkout@v3

    # Deploy client to Vercel
    - name: Deploy Client to Vercel
      id: deploy-client
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_CLIENT_PROJECT_ID }}
        working-directory: ./client
        vercel-args: '--prod'
        alias-domains: |
          writeitupx.vercel.app

    # Deploy server to Vercel
    - name: Deploy Server to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_SERVER_PROJECT_ID }}
        working-directory: ./server
        vercel-args: '--prod'
        alias-domains: |
          api.writeitupx.vercel.app
